const collection = {
  paintings: {
    500: {
      id: 500,
      title: "Integration",
      imgUrl: "https://artbykuze.imgix.net/integration.jpg",
      dimensions: "100cm x 100cm",
      medium: "acrylic on canvas",
      framed: "105cm x 105cm",
      price: "€ 3500",
      buyHere:
        "https://www.apgalerija.lt/product-page/au%C5%A1rin%C4%97-kuznecovait%C4%97-kuze-integracija-2019",
    },
    501: {
      id: 501,
      title: "Apocalypse",
      imgUrl: "https://artbykuze.imgix.net/apocalypse.jpg",
      dimensions: "100cm x 100cm",
      medium: "acrylic on canvas",
      framed: "unframed",
      price: "€ 3500",
      buyHere:
        "https://www.apgalerija.lt/product-page/au%C5%A1rin%C4%97-kuznecovait%C4%97-kuze-apokalips%C4%97-2019",
    },
    502: {
      id: 502,
      title: "Biological",
      imgUrl: "https://artbykuze.imgix.net/biological.jpg",
      dimensions: "100cm x 100cm",
      medium: "acrylic on canvas",
      framed: "105cm x 105cm",
      price: "SOLD",
      buyHere: "",
    },
    503: {
      id: 503,
      title: "Usher's Quay",
      imgUrl: "https://artbykuze.imgix.net/ushersquay.jpg",
      dimensions: "120cm x 120cm",
      medium: "acrylic on canvas",
      framed: "125cm x 125cm",
      price: "RESERVED",
      buyHere: "",
    },
    504: {
      id: 504,
      title: "Tribal Disco",
      imgUrl: "https://artbykuze.imgix.net/tribaldisco.jpg",
      dimensions: "100cm x 40cm",
      medium: "acrylic on canvas",
      framed: "116m x 57cm",
      price: "€ 3200",
      buyHere:
        "https://www.apgalerija.lt/product-page/au%C5%A1rin%C4%97-kuznecovait%C4%97-kuze-gen%C4%8Di%C5%B3-diskoteka-2019",
    },
    505: {
      id: 505,
      title: "Behind the bushes",
      imgUrl: "https://artbykuze.imgix.net/behindthebushes.jpg",
      dimensions: "100cm x 40cm",
      medium: "acrylic on canvas",
      framed: "116m x 57cm",
      price: "€ 3200",
      buyHere:
        "https://www.apgalerija.lt/product-page/au%C5%A1rin%C4%97-kuznecovait%C4%97-kuze-u%C5%BE-kr%C5%ABm%C5%B3-2019",
    },
    506: {
      id: 506,
      title: "Where we were",
      imgUrl: "https://artbykuze.imgix.net/wherewewere.jpg",
      dimensions: "120cm x 120cm",
      medium: "acrylic on canvas",
      framed: "125m x 125cm",
      price: "RESERVED",
      buyHere: "",
    },
    507: {
      id: 507,
      title: "Father of many",
      imgUrl: "https://artbykuze.imgix.net/fatherofmany.jpg",
      dimensions: "120cm x 80cm",
      medium: "acrylic on canvas",
      framed: "125m x 85cm",
      price: "RESERVED",
      buyHere: "",
    },
    508: {
      id: 508,
      title: "Mother of two",
      imgUrl: "https://artbykuze.imgix.net/motheroftwo.jpg",
      dimensions: "120cm x 80cm",
      medium: "acrylic on canvas",
      framed: "125m x 85cm",
      price: "RESERVED",
      buyHere: "",
    },
    509: {
      id: 509,
      title: "Playing chess with a goose",
      imgUrl: "https://artbykuze.imgix.net/playingchesswithagoose.jpg",
      dimensions: "70cm x 100cm",
      medium: "acrylic on canvas",
      framed: "75m x 105cm",
      price: "€ 2200",
      buyHere:
        "https://www.thedoorwaygallery.com/artists/ausrine-kuze/playing-chess-with-a-goat/37527/",
    },
    510: {
      id: 510,
      title: "Riding the bull",
      imgUrl: "https://artbykuze.imgix.net/ridingthebull.jpg",
      dimensions: "50cm x 70cm",
      medium: "acrylic on canvas",
      framed: "66m x 86cm",
      price: "RESERVED",
      buyHere: "",
    },
    511: {
      id: 511,
      title: "King of the jungle",
      imgUrl: "https://artbykuze.imgix.net/kingofthejungle.jpg",
      dimensions: "50cm x 70cm",
      medium: "acrylic on canvas",
      framed: "66m x 86cm",
      price: "SOLD",
      buyHere: "",
    },
    512: {
      id: 512,
      title: "Chit chat in the bath",
      imgUrl: "https://artbykuze.imgix.net/chitchatinthebath.jpg",
      dimensions: "30cm x 30cm",
      medium: "acrylic on canvas",
      framed: "35cm x 35cm",
      price: "€ 590",
      buyHere:
        "https://www.thedoorwaygallery.com/artists/ausrine-kuze/chit-chat-in-the-bath/37526/",
    },
    513: {
      id: 513,
      title: "Investigation",
      imgUrl: "https://artbykuze.imgix.net/investigation.jpg",
      dimensions: "40cm x 20cm",
      medium: "acrylic on canvas",
      framed: "54cm x 34cm",
      price: "RESERVED",
      buyHere: "",
    },
    514: {
      id: 514,
      title: "Serenade",
      imgUrl: "https://artbykuze.imgix.net/serenade.jpg",
      dimensions: "40cm x 20cm",
      medium: "acrylic on canvas",
      framed: "56cm x 36cm",
      price: "RESERVED",
      buyHere: "",
    },
    515: {
      id: 515,
      title: "A princes",
      imgUrl: "https://artbykuze.imgix.net/aprinces.jpg",
      dimensions: "40cm x 20cm",
      medium: "acrylic on canvas",
      framed: "45cm x 25cm",
      price: "€ 590",
      buyHere:
        "https://www.thedoorwaygallery.com/artists/ausrine-kuze/a-princess-/37524/",
    },
    516: {
      id: 516,
      title: "Yellow doughnut",
      imgUrl: "https://artbykuze.imgix.net/yellowdonut.jpg",
      dimensions: "40cm x 20cm",
      medium: "acrylic on canvas",
      framed: "56cm x 36cm",
      price: "€ 590",
      buyHere:
        "https://www.thedoorwaygallery.com/artists/ausrine-kuze/yellow-dougnut/31216/",
    },
    517: {
      id: 517,
      title: "Cactus Man",
      imgUrl: "https://artbykuze.imgix.net/cactusman.jpg",
      dimensions: "40cm x 20cm",
      medium: "acrylic on canvas",
      framed: "45cm x 25cm",
      price: "€ 590",
      buyHere:
        "https://www.thedoorwaygallery.com/artists/ausrine-kuze/cactus-man/37525/",
    },
  },
  drawings: {
    200: {
      id: 200,
      title: "These flowers has always been here",
      imgUrl: "https://artbykuze.imgix.net/thoseflowershasalwaysbeenhere.jpg",
      dimensions: "30cm x 42cm",
      medium: "mixed media",
      framed: "47cm x 61.5cm",
      price: "€ 450",
      buyHere: "",
    },
    201: {
      id: 201,
      title: "The magic, the beauty lives in your mind",
      imgUrl: "https://artbykuze.imgix.net/themagicthebeauty.jpg",
      dimensions: "30cm x 42cm",
      medium: "mixed media",
      framed: "47cm x 61.5cm",
      price: "€ 450",
      buyHere: "",
    },
    202: {
      id: 202,
      title: "Completed, yet ongoing",
      imgUrl: "https://artbykuze.imgix.net/completedyetongoing.jpg",
      dimensions: "22cm x 30cm",
      medium: "mixed media",
      framed: "38cm x 47cm",
      price: "RESERVED",
      buyHere: "",
    },
  },
};

export default collection;
